name: pre_commit

on:
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master
      - stable
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v3
    - name: Configure Git
      run: |
        git config --global color.diff.meta       "11"
        git config --global color.diff.frag       "magenta bold"
        git config --global color.diff.func       "146 bold"
        git config --global color.diff.commit     "yellow bold"
        git config --global color.diff.old        "red bold"
        git config --global color.diff.new        "green bold"
        git config --global color.diff.whitespace "red reverse"

        git config --global diff.wsErrorHighlight "all"
    - uses: actions/setup-python@v3.0.0
    - uses: pre-commit/action@v2.0.3
